### ISSUE TITLE
i am stuck with requirements . 

### ISSUE THREAD

**Issue by LORDshiVSaveME** [coffinxp/loxs#17]
hey bro . hope you are doing well . as this tool need  requirements are not full filled .. this shows error . 
i can't able to install all requirements webdriver_manager
selenium
aiohttp
beautifulsoup4
colorama. 
rich
requests
gitpython
prompt_toolkit
pyyaml
Flask
in kali linux . would you help me to install all requirements  in kali linux .. that would be a great help for me .. 
. this shows this error 
: 
python lostsec.py            
Traceback (most recent call last):
  File "/home/loke/work/tool/lostools/lostsec.py", line 49, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by LORDshiVSaveME** [comment]
sudo python lostsec.py -h 
[sudo] password for loke: 
Traceback (most recent call last):
  File "/home/loke/work/tool/lostools/lostsec.py", line 38, in <module>
    from bs4 import BeautifulSoup
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
  File "<frozen zipimport>", line 111, in find_spec
  File "<frozen importlib._bootstrap>", line 675, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 822, in spec_from_file_location
  File "<frozen zipimport>", line 170, in get_filename
  File "<frozen zipimport>", line 708, in _get_module_code
  File "<frozen zipimport>", line 637, in _compile_source
  File "/usr/local/lib/python3.12/dist-packages/beautifulsoup4-4.3.2-py3.12.egg/bs4/__init__.py", line 175
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by coffinxp** [comment]
are you using ubuntu or debian ? if yes then install all manually by pip its easy,.

**Comment by LORDshiVSaveME** [comment]
i am using kali linux . i think debain
