### ISSUE TITLE
NEW ISSUES

### ISSUE THREAD

**Issue by Meet46** [coffinxp/loxs#2]
idk is it me or something else i tried the same website the you use on your demo video i did everything same as you did and i tried on many other websites But i got the same error everytime i use  if i am wrong or using the tool  wrong please let me know but i am facing this issue:-[i] Starting scan...
[i] Checking for WAF on target URLs...
[+] No WAF detected.

[i] Payloads loaded from file.
[i] Scanning with payload: jaVasCript:/*-/*`/*\`/*'/*"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert()//>\x3e

Traceback (most recent call last):
  File "/home/kali/lostools/lostsec.py", line 1565, in <module>
    main()
  File "/home/kali/lostools/lostsec.py", line 1561, in main
    handle_selection(choice)
  File "/home/kali/lostools/lostsec.py", line 1532, in handle_selection
    run_xss_scanner()
  File "/home/kali/lostools/lostsec.py", line 918, in run_xss_scanner
    main()
  File "/home/kali/lostools/lostsec.py", line 914, in main
    scanner.run()
  File "/home/kali/lostools/lostsec.py", line 783, in run
    asyncio.run(self.scan())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kali/lostools/lostsec.py", line 761, in scan
    self.process_tasks(done)
  File "/home/kali/lostools/lostsec.py", line 725, in process_tasks
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 128.0.6613.113 with binary path /usr/bin/chromium
Stacktrace:
#0 0x55a2683774e3 <unknown>
#1 0x55a2680a6c76 <unknown>
#2 0x55a2680d404a <unknown>
#3 0x55a2680cf4a1 <unknown>
#4 0x55a2680cc029 <unknown>
#5 0x55a26810accc <unknown>
#6 0x55a26810a47f <unknown>
#7 0x55a268101de3 <unknown>
#8 0x55a2680d72dd <unknown>
#9 0x55a2680d834e <unknown>
#10 0x55a2683373e4 <unknown>
#11 0x55a26833b3d7 <unknown>
#12 0x55a268345b20 <unknown>
#13 0x55a26833c023 <unknown>
#14 0x55a26830a1aa <unknown>
#15 0x55a2683606b8 <unknown>
#16 0x55a268360847 <unknown>
#17 0x55a268370243 <unknown>
#18 0x7f3338b4cdab <unknown>

**Comment by coffinxp** [comment]
its chrome driver error i tested on other system working good make sure install driver manully

**Comment by Meet46** [comment]
can you please tell me How i've tried everything but i couldn't find the solution
