### ISSUE TITLE
i got an error while i run a tool loxs.py

### ISSUE THREAD

**Issue by One11on** [coffinxp/loxs#27]
I use a python virtual environment

ERROR:
Traceback (most recent call last):
  File "/root/tools/xss/lostools/loxs.py", line 1736, in <module>
    main()
  File "/root/tools/xss/lostools/loxs.py", line 1732, in main
    handle_selection(choice)
  File "/root/tools/xss/lostools/loxs.py", line 1709, in handle_selection
    run_xss_scanner()
  File "/root/tools/xss/lostools/loxs.py", line 1208, in run_xss_scanner
    main()
  File "/root/tools/xss/lostools/loxs.py", line 1202, in main
    scanner.run()
  File "/root/tools/xss/lostools/loxs.py", line 1103, in run
    asyncio.run(self.scan())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/tools/xss/lostools/loxs.py", line 1073, in scan
    self.process_tasks(done)
  File "/root/tools/xss/lostools/loxs.py", line 1038, in process_tasks
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/root/tools/myenv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 128.0.6613.113 with binary path /usr/bin/chromium
Stacktrace:
#0 0x555aeaa8e4e3 <unknown>
#1 0x555aea7bdc76 <unknown>
#2 0x555aea7eb04a <unknown>
#3 0x555aea7e64a1 <unknown>
#4 0x555aea7e3029 <unknown>
#5 0x555aea821ccc <unknown>
#6 0x555aea82147f <unknown>
#7 0x555aea818de3 <unknown>
#8 0x555aea7ee2dd <unknown>
#9 0x555aea7ef34e <unknown>
#10 0x555aeaa4e3e4 <unknown>
#11 0x555aeaa523d7 <unknown>
#12 0x555aeaa5cb20 <unknown>
#13 0x555aeaa53023 <unknown>
#14 0x555aeaa211aa <unknown>
#15 0x555aeaa776b8 <unknown>
#16 0x555aeaa77847 <unknown>
#17 0x555aeaa87243 <unknown>
#18 0x7fd210200732 <unknown>

**Comment by One11on** [comment]
![Screenshot 2024-10-08 015251](https://github.com/user-attachments/assets/6b2bc65f-09c5-46f5-81ff-db5e34bc5ca0)

**Comment by coffinxp** [comment]
uninstall old driver and install latest one
