### ISSUE TITLE
Error when running loxs.py

### ISSUE THREAD

**Issue by wh1ter0ze** [coffinxp/loxs#29]
Traceback (most recent call last):
  File "/root/loxs/loxs.py", line 51, in <module>
    import aiohttp
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/helpers.py", line 98, in <module>
    old_debug = coroutines._DEBUG  # type: ignore
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio.coroutines' has no attribute '_DEBUG'

**Comment by coffinxp** [comment]
are u using ubuntu debian

**Comment by wh1ter0ze** [comment]
> are u using ubuntu debian

I'm using kali linux

**Comment by ghost** [comment]
Hello,

try to update aiohttp : 

pip install --upgrade aiohttp

**Comment by wh1ter0ze** [comment]
> pip install --upgrade aiohttp

Worked, thanks

**Comment by 57ayush76** [comment]
> Hello,
> 
> try to update aiohttp :
> 
> pip install --upgrade aiohttp

my problem get solved but new problem get arised 
![Uploading Screenshot 2024-10-26 005803.png…]()
