### ISSUE TITLE
can't initiate xss scan

### ISSUE THREAD

**Issue by CyberPro010** [coffinxp/loxs#34]
when i start i see this error:

[i] Starting scan...

┌───────────────────────────────────────────────┐
│ → Scanning URL: https://site.com/search?q= │
└───────────────────────────────────────────────┘

Traceback (most recent call last):
  File "/home/user/tools/loxs/loxs.py", line 1754, in <module>
    main()
  File "/home/user/tools/loxs/loxs.py", line 1747, in main
    handle_selection(choice)
  File "/home/user/tools/loxs/loxs.py", line 1724, in handle_selection
    run_xss_scanner()
  File "/home/user/tools/loxs/loxs.py", line 1153, in run_xss_scanner
    main()
  File "/home/user/tools/loxs/loxs.py", line 1143, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/loxs/loxs.py", line 1003, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 129.0.6668.89 with binary path /usr/bin/chromium
Stacktrace:
#0 0x5642334134e3 <unknown>
#1 0x564233142c76 <unknown>
#2 0x56423317004a <unknown>
#3 0x56423316b4a1 <unknown>
#4 0x564233168029 <unknown>
#5 0x5642331a6ccc <unknown>
#6 0x5642331a647f <unknown>
#7 0x56423319dde3 <unknown>
#8 0x5642331732dd <unknown>
#9 0x56423317434e <unknown>
#10 0x5642333d33e4 <unknown>
#11 0x5642333d73d7 <unknown>
#12 0x5642333e1b20 <unknown>
#13 0x5642333d8023 <unknown>
#14 0x5642333a61aa <unknown>
#15 0x5642333fc6b8 <unknown>
#16 0x5642333fc847 <unknown>
#17 0x56423340c243 <unknown>
#18 0x7f65dc791732 <unknown>

**Comment by ghost** [comment]
Hello,

You didn't install chromedriver, download it and try again ;) also make sure to install all requirements : 

pip install -r requirements.txt

hexsh1dow

**Comment by ghost** [comment]
i have the same issue and i have chrome driver installed

**Comment by ghost** [comment]
Hello,

Can you send the version of chromedriver you have ? 

Everything is explained on the readme file Make sure everything is good | If it still doesn't work, reinstall ChromeDriver and make sure to install all requirements

hexsh1dow

**Comment by ghost** [comment]
ChromeDriver 126.0.6478.126

**Comment by ghost** [comment]
when i reinstalled chromedriver while following the directions in the readme, it installs chromedriver 128.0.6613.119. with this version i get a different error message which reads as follows:

raceback (most recent call last):
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1754, in <module>
    main()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1747, in main
    handle_selection(choice)
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1724, in handle_selection
    run_xss_scanner()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1153, in run_xss_scanner
    main()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1143, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1003, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'


this only happens when trying to do an XSS scan

**Comment by ghost** [comment]
Hey,

upgrade selenium :

 pip install --upgrade selenium

hexsh1dow

**Comment by ghost** [comment]
okay, just tried that and not its back to saying 

Traceback (most recent call last):
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1754, in <module>
    main()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1747, in main
    handle_selection(choice)
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1724, in handle_selection
    run_xss_scanner()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1153, in run_xss_scanner
    main()
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1143, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ciznaa/Documents/tools/loxs/loxs.py", line 1003, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/ciznaa/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 126.0.6478.126 with binary path /usr/bin/chromium
Stacktrace:
#0 0x55b7de8f34e3 <unknown>
#1 0x55b7de622c76 <unknown>
#2 0x55b7de65004a <unknown>
#3 0x55b7de64b4a1 <unknown>
#4 0x55b7de648029 <unknown>
#5 0x55b7de686ccc <unknown>
#6 0x55b7de68647f <unknown>
#7 0x55b7de67dde3 <unknown>
#8 0x55b7de6532dd <unknown>
#9 0x55b7de65434e <unknown>
#10 0x55b7de8b33e4 <unknown>
#11 0x55b7de8b73d7 <unknown>
#12 0x55b7de8c1b20 <unknown>
#13 0x55b7de8b8023 <unknown>
#14 0x55b7de8861aa <unknown>
#15 0x55b7de8dc6b8 <unknown>
#16 0x55b7de8dc847 <unknown>
#17 0x55b7de8ec243 <unknown>
#18 0x7f5eb0b07dab <unknown>


any other suggestions? maybe i have to downgrade chrome to verison 114

**Comment by ghost** [comment]
Hello,

Yeah try to do that

hexsh1dow

**Comment by CyberPro010** [comment]
> Hello,
> 
> Yeah try to do that
> 
> hexsh1dow

how to downgrade man ? i reinstalled python and most of things are fixed and how to downgrade ?

**Comment by ghost** [comment]
Hello,

uninstall and reinstall chrome driver and put it on /usr/bin folder

hexsh1dow

**Comment by CyberPro010** [comment]
> Hello,
> 
> uninstall and reinstall chrome driver and put it on /usr/bin folder
> 
> hexsh1dow

could you please give me the commands ?

**Comment by ghost** [comment]
Hello,

follow this tutorial : https://www.youtube.com/watch?v=dz59GsdvUF8

hexsh1dow

**Comment by CyberPro010** [comment]
My linux got destroyed 😂 so installing it again

**Comment by CyberPro010** [comment]
> Hello,
> 
> follow this tutorial : https://www.youtube.com/watch?v=dz59GsdvUF8
> 
> hexsh1dow

bruh i am using linux

**Comment by coffinxp** [comment]
dont run with root permission chrome not work on root.make sure your dir is not root

**Comment by CyberPro010** [comment]
> dont run with root permission chrome not work on root.make sure your dir is not root

ok let's see
