### ISSUE TITLE
EXEC FORM ERROR

### ISSUE THREAD

**Issue by jsqli** [coffinxp/loxs#38]
[i] Starting scan...

┌──────────────────────────────────────┐
│  → Scanning URLs:
└──────────────────────────────────────┘

Traceback (most recent call last):
  File "/home/federal/Downloads/loxs/loxs.py", line 1791, in <module>
    main()
  File "/home/federal/Downloads/loxs/loxs.py", line 1784, in main
    handle_selection(choice)
  File "/home/federal/Downloads/loxs/loxs.py", line 1760, in handle_selection
    run_xss_scanner()
  File "/home/federal/Downloads/loxs/loxs.py", line 1160, in run_xss_scanner
    main()
  File "/home/federal/Downloads/loxs/loxs.py", line 1150, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/federal/Downloads/loxs/loxs.py", line 1010, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/130.0.6723.58/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'

^^ running anything leads to this error. running on parrotos.

**Comment by coffinxp** [comment]
install all requirements and chrome driver properly

**Comment by jsqli** [comment]
i have and chrome webdriver is installed too its in my .wdm path and also /usr/bin
