### ISSUE TITLE
can't initiate xss scan

### ISSUE THREAD

**Issue by CyberPro010** [coffinxp/loxs#42]
hex don't ignore me my problem is still same if you don't fix it i will stop using this in my team and me also and this is the issue whenever i try to start xss scan : 
[i] Starting scan...

┌──────────────────────────────────────────────────────────┐
│ → Scanning URL: https://site.com/product-details?id= │
└──────────────────────────────────────────────────────────┘

Traceback (most recent call last):
  File "/home/user/tools/loxs/loxs.py", line 1754, in <module>
    main()
  File "/home/user/tools/loxs/loxs.py", line 1747, in main
    handle_selection(choice)
  File "/home/user/tools/loxs/loxs.py", line 1724, in handle_selection
    run_xss_scanner()
  File "/home/user/tools/loxs/loxs.py", line 1153, in run_xss_scanner
    main()
  File "/home/user/tools/loxs/loxs.py", line 1143, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/loxs/loxs.py", line 1003, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5572ba8c710a <unknown>
#1 0x5572ba3e2460 <unknown>
#2 0x5572ba3cab00 <unknown>
#3 0x5572ba3ca7ed <unknown>
#4 0x5572ba3c887c <unknown>
#5 0x5572ba3c8eba <unknown>
#6 0x5572ba3c7851 <unknown>
#7 0x5572ba3cfaaf <unknown>
#8 0x5572ba3c759b <unknown>
#9 0x5572ba3ca4ba <unknown>
#10 0x5572ba3c887c <unknown>
#11 0x5572ba3c8eba <unknown>
#12 0x5572ba3c7851 <unknown>
#13 0x5572ba3be2d7 <unknown>
#14 0x5572ba3c759b <unknown>
#15 0x5572ba3c6ec2 <unknown>
#16 0x5572ba3c6995 <unknown>
#17 0x5572ba3e464e <unknown>
#18 0x5572ba3b7dee <unknown>
#19 0x5572ba3b7956 <unknown>
#20 0x5572ba45f35c <unknown>
#21 0x5572ba45e7a6 <unknown>
#22 0x5572ba452db3 <unknown>
#23 0x5572ba421c10 <unknown>
#24 0x5572ba422bee <unknown>
#25 0x5572ba89339b <unknown>
#26 0x5572ba897338 <unknown>
#27 0x5572ba880ebc <unknown>
#28 0x5572ba897eb7 <unknown>
#29 0x5572ba86610f <unknown>
#30 0x5572ba8b5828 <unknown>
#31 0x5572ba8b59f0 <unknown>
#32 0x5572ba8c5f86 <unknown>
#33 0x7f06d47b3732 <unknown>

**Comment by coffinxp** [comment]
its chrome driver issue uninstall old one and install new step by step written on readme and make sure put chromedriver binary in /usr/bin

**Comment by CyberPro010** [comment]
> its chrome driver issue uninstall old one and install new step by step written on readme and make sure put chromedriver binary in /usr/bin

man big fan of your skills
