### ISSUE TITLE
It crashed. Please Check error message 

### ISSUE THREAD

**Issue by brightokine** [coffinxp/loxs#54]
Traceback (most recent call last):
  File "/home/tools/loxs/loxs.py", line 2107, in <module>
    main()                                                          File "/home/tools/loxs/loxs.py", line 2100, in main
    handle_selection(choice)
  File "/home/tools/loxs/loxs.py", line 2072, in handle_selection     run_xss_scanner()
  File "/home/tools/loxs/loxs.py", line 1190, in run_xss_scanner      main()
  File "/home/tools/loxs/loxs.py", line 1173, in main                 vulnerable_urls, scanned = run_scan([url], payload_file, timeout, scan_state)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                     File "/home/tools/loxs/loxs.py", line 1021, in run_scan             driver_pool.put(create_driver())
                    ^^^^^^^^^^^^^^^                                 File "/home/tools/loxs/loxs.py", line 963, in create_driver         return webdriver.Chrome(service=driver_service, options=chrome_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver'

**Comment by moin-gun** [comment]
@brightokine looks like you don't have chrome driver installed as per last line in your error logs.

**Comment by brightokine** [comment]
I have 

┌──(brightnii)(kali㉿localhost)-[/home/tools/loxs]
└─$ ls /home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver

But still not working. I'm using Kali in termux.

**Comment by coffinxp** [comment]
install latest chrome driver that given in readme file your is 114 version
