### ISSUE TITLE
Error Selenium Webdriver

### ISSUE THREAD

**Issue by Conato1** [coffinxp/loxs#60]
Hello ... anyone can help me with this error

Traceback (most recent call last):
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 242, in <module>
    run_xss_scanner()
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 240, in run_xss_scanner
    main()
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 229, in main
    vulnerable_urls, scanned, start_time = run_scan([url], payload_file, concurrency=10, timeout=1)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 112, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/kali/.wdm/drivers/chromedriver/linux64/131.0.6778.69/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'

**Comment by Conato1** [comment]
Traceback (most recent call last):
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 242, in <module>
    run_xss_scanner()
  File "/home/kali/Downloads/Xss/loxs/tool/xss.py", line 32, in run_xss_scanner
    console = Console()
              ^^^^^^^
NameError: name 'Console' is not defined

**Comment by moin-gun** [comment]
Hey @Conato1 can you please reinstall tool and try to run it in virtual environment.

**Comment by pedrojimenezrd** [comment]
igual solo me funciona el lfi: lo hice en un entorno virtual he provado en dos kali y nada: 
Traceback (most recent call last):
  File "/home/andy/herramientas/loxs/tool/xss.py", line 242, in <module>
    run_xss_scanner()
  File "/home/andy/herramientas/loxs/tool/xss.py", line 240, in run_xss_scanner
    main()
  File "/home/andy/herramientas/loxs/tool/xss.py", line 229, in main
    vulnerable_urls, scanned, start_time = run_scan([url], payload_file, concurrency=10, timeout=1)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/herramientas/loxs/tool/xss.py", line 112, in run_scan
    driver = webdriver.Chrome(service=driver_service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/andy/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 126.0.6478.126 with binary path /usr/bin/chromium
Stacktrace:
#0 0x556baf8e74e3 <unknown>
#1 0x556baf616c76 <unknown>
#2 0x556baf64404a <unknown>
#3 0x556baf63f4a1 <unknown>
#4 0x556baf63c029 <unknown>
#5 0x556baf67accc <unknown>
#6 0x556baf67a47f <unknown>
#7 0x556baf671de3 <unknown>
#8 0x556baf6472dd <unknown>
#9 0x556baf64834e <unknown>
#10 0x556baf8a73e4 <unknown>
#11 0x556baf8ab3d7 <unknown>
#12 0x556baf8b5b20 <unknown>
#13 0x556baf8ac023 <unknown>
#14 0x556baf87a1aa <unknown>
#15 0x556baf8d06b8 <unknown>
#16 0x556baf8d0847 <unknown>
#17 0x556baf8e0243 <unknown>
#18 0x7f3387e97dab <unknown>

**Comment by Conato1** [comment]
I've already solved this issue using this

first you can delete the .wmd folder and run this command

pip3 uninstall webdriver-manager
pip3 install webdriver-manager
