### ISSUE TITLE
plz solve this problame

### ISSUE THREAD

**Issue by tajuislam** [coffinxp/loxs#62]
┌──────────────────────────────────────────────────────────────────────────────────┐
│ → Scanning URL: https://blog.glia.com/category/technology/page/3/?filter_by=FUZZ │
└──────────────────────────────────────────────────────────────────────────────────┘

Traceback (most recent call last):
  File "/root/xsstools/loxs/loxs.py", line 2104, in <module>
    main()
  File "/root/xsstools/loxs/loxs.py", line 2097, in main
    handle_selection(choice)
  File "/root/xsstools/loxs/loxs.py", line 2069, in handle_selection
    run_xss_scanner()
  File "/root/xsstools/loxs/loxs.py", line 1187, in run_xss_scanner
    main()
  File "/root/xsstools/loxs/loxs.py", line 1177, in main
    vulnerable_urls, scanned = run_scan([url], payload_file, concurrency, timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/xsstools/loxs/loxs.py", line 1018, in run_scan
    driver_pool.put(create_driver())
                    ^^^^^^^^^^^^^^^
  File "/root/xsstools/loxs/loxs.py", line 963, in create_driver
    return webdriver.Chrome(service=driver_service, options=chrome_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/root/xsstools/loxs/venvpath/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 129.0.6668.89 with binary path /usr/bin/chromium
Stacktrace:
#0 0x562f84bb24e3 <unknown>
#1 0x562f848e1c76 <unknown>
#2 0x562f8490f04a <unknown>
#3 0x562f8490a4a1 <unknown>
#4 0x562f84907029 <unknown>
#5 0x562f84945ccc <unknown>
#6 0x562f8494547f <unknown>
#7 0x562f8493cde3 <unknown>
#8 0x562f849122dd <unknown>
#9 0x562f8491334e <unknown>
#10 0x562f84b723e4 <unknown>
#11 0x562f84b763d7 <unknown>
#12 0x562f84b80b20 <unknown>
#13 0x562f84b77023 <unknown>
#14 0x562f84b451aa <unknown>
#15 0x562f84b9b6b8 <unknown>
#16 0x562f84b9b847 <unknown>
#17 0x562f84bab243 <unknown>
#18 0x7f71ea3e7112 <unknown>

**Comment by moin-gun** [comment]
hi @tajuislam Please run below commands

First -> https://github.com/coffinxp/loxs?tab=readme-ov-file#chrome-installation
Second -> https://github.com/coffinxp/loxs?tab=readme-ov-file#chrome-driver-installation

**Comment by Conato1** [comment]
I've already solved this issue using this

first you can delete the .wmd folder and run this command

pip3 uninstall webdriver-manager
pip3 install webdriver-manager
