### ISSUE TITLE
Xss option is not working

### ISSUE THREAD

**Issue by LF-H0** [coffinxp/loxs#63]
[i] Starting scan...
                                                                      
┌─────────────────────────────────────────────────────────────┐
│ → Scanning URL: http://testphp.vulnweb.com/search.php?test= │
└─────────────────────────────────────────────────────────────┘

Traceback (most recent call last):
  File "/home/kali/tools/loxs/tool/xss.py", line 242, in <module>         run_xss_scanner()                                                   File "/home/kali/tools/loxs/tool/xss.py", line 240, in run_xss_scanner                                                                        main()                                                              File "/home/kali/tools/loxs/tool/xss.py", line 229, in main             vulnerable_urls, scanned, start_time = run_scan([url], payload_file, concurrency=10, timeout=1)                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           File "/home/kali/tools/loxs/tool/xss.py", line 112, in run_scan         driver = webdriver.Chrome(service=driver_service, options=chrome_options)                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 File "/home/kali/tools/loxs/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__                   super().__init__(                                                   File "/home/kali/tools/loxs/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__                 self.service.start()
  File "/home/kali/tools/loxs/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 104, in start                       self._start_process(self._path)
  File "/home/kali/tools/loxs/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver'

**Comment by coffinxp** [comment]
you are using old chrome driver version install new one by following readme file steps
