### ISSUE TITLE
Windows Curses Python module

### ISSUE THREAD

**Issue by MrBlue-Official-Account** [coffinxp/loxs#73]
**If you run the tool on Windows and get this error:**

```sh
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Tools\loxs\loxs.py", line 33, in <module>
    from curses import panel
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```
**paste to the terminal:**
```sh
pip install windows-curses
```

**Comment by ghost** [comment]
Hello,

Please check issue #71. I’ve answered your question there.

Best regards,
hexsh1dow
